name: Run first test in CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: Folder
        run: cd ./lesson_13
      - name: Dependencies
        working-directory: ./lesson_13tpekmnfn
        run: npm i
      - name: Run tests
        working-directory: ./lesson_13
        run: npm test